name: CI/CD for Canvas Apps
trigger: none

stages:
  - stage: export_solution
    variables:
      SolutionName: 'ALMDemo'
      SolutionOutput: 'ALMDemo.zip'
      PowerPlatformSPN: 'CS Apps Dev'
    jobs:
    - job: export_solution
      displayName: Export Solution
      pool:
        vmImage: vs2017-win2016
      steps:
      - checkout: self
        persistCredentials: True
      - task: PowerPlatformToolInstaller@0
        displayName: 'Power Platform Tool Installer '
      - task: PowerPlatformWhoAmi@0
        displayName: 'Power Platform WhoAmI '
        inputs:
          authenticationType: 'PowerPlatformSPN'
          PowerPlatformSPN: '$(PowerPlatformSPN)'
      - task: PowerPlatformExportSolution@0
        displayName: 'Power Platform Export Unmanaged Solution '
        inputs:
          authenticationType: 'PowerPlatformSPN'
          PowerPlatformSPN: '$(PowerPlatformSPN)'
          SolutionName: '$(SolutionName)'
          SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName).zip'
          AsyncOperation: true
          MaxAsyncWaitTime: '240'
      - task: PowerPlatformChecker@0
        displayName: 'Power Platform Checker '
        inputs:
          PowerPlatformSPN: '$(PowerPlatformSPN)'
          FilesToAnalyze: $(Build.ArtifactStagingDirectory)/$(SolutionName).zip
          RuleSet: 0ad12346-e108-40b8-a956-9a8f95ea18c9
          ArtifactDestinationName: AppsCheckerAnalysisLogs
      - task: PowerPlatformUnpackSolution@0
        displayName: 'Power Platform Unpack Solution '
        inputs:
          SolutionInputFile: $(Build.ArtifactStagingDirectory)/$(SolutionName).zip
          SolutionTargetFolder: $(Build.SourcesDirectory)\$(SolutionName)
      - task: CmdLine@2
        displayName: Commit Solution
        inputs:
          script: >-
            echo commit all changes
            
            git config user.email "powerapps@microsoft.com"
            git config user.name "Automatic Build"
            git checkout main
            git add --all
            git commit -m "export solution"

            echo push code to new repo

            git -c http.extraheader="AUTHORIZATION: Bearer $(System.AccessToken)" push origin main
      - task: PowerPlatformExportSolution@0
        displayName: Power Platform Export Managed Solution
        inputs:
          authenticationType: PowerPlatformSPN
          PowerPlatformSPN: '$(PowerPlatformSPN)'
          SolutionName: $(SolutionName)
          SolutionOutputFile: $(Build.ArtifactStagingDirectory)/$(SolutionName)_managed.zip
          Managed: true
          MaxAsyncWaitTime: 240
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'